// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazerApp.Data;

namespace RazerApp.Migrations
{
    [DbContext(typeof(RazerAppContext))]
    partial class RazerAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazerApp.Models.Cricket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IplTeam")
                        .IsRequired();

                    b.Property<string>("PlayerName")
                        .IsRequired();

                    b.Property<int>("PlayerNum");

                    b.Property<string>("Position")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Cricket");
                });
#pragma warning restore 612, 618
        }
    }
}
